services:
  db:
    image: postgres:17
    container_name: hackathon-postgres
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "admin"
      POSTGRES_DB: "hackathon-back"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 3

  redis:
    image: redis:8.2.1
    container_name: hackathon-redis
    environment:
      - REDIS_PASSWORD=admin
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "admin", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5

  mailhog:
    image: mailhog/mailhog
    container_name: hackathon-mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: hackathon-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9200 || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 10
  hackathon-back:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hackathon-back
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ./config/config.docker.yml:/app/config/config.docker.yml
    environment:
      CONFIG_PATH: "/app/config/config.docker.yml"

volumes:
  postgres_data:
  redis_data:
  elasticsearch_data:
