app:
  service_name: "hackathon-back"
  version: 0.1.0
log:
  level: "debug"
  format_json: false
  rotation:
    file: "./hackathon-back.log"
    max_size: 10
    max_backups: 3
    max_age: 7
database:
  host: "hackathon-postgres"
  port: 5432
  user: "admin"
  password: "admin"
  name: "hackathon-back"
  ssl_mode: "disable"
  max_conns: 10
  min_conns: 2
  migration:
    path: "./migrations"
    auto_apply: true
redis:
  enable: true
  host: "hackathon-redis"
  port: 6379
  password: "admin"
  db: 0
http_server:
  host: "0.0.0.0"
  port: 8080
  base_path: "/api"
  timeout:
    request: 3s
    read: 5s
    write: 5s
    idle: 5s
  cors:
    enabled: false
    allow_all_origins: true
    allow_origins: [ ]
    allow_methods:
      - "GET"
      - "POST"
      - "PUT"
      - "PATCH"
      - "DELETE"
      - "OPTIONS"
    allow_headers:
      - "Origin"
      - "Content-Type"
      - "Accept"
      - "Authorization"
    expose_headers:
      - "Content-Length"
    allow_credentials: true
    max_age: 12h
    allow_websockets: true
    allow_files: false
  jwt:
    access_token_ttl: 20m
    refresh_token_ttl: 43200m
mailer:
  host: "hackathon-mailhog"
  port: 1025
  username: ""
  password: ""
  from: "hackathon-back"
  use_tls: false
key:
  public: "./ecdsa_public.pem"
  private: "./ecdsa_private.pem"


minio:
  endpoint: "localhost:9000"
  access_key: "minioadmin"
  secret_key: "minioadmin"
  bucket_name: "user-photos"
  base_url: "http://localhost:9000"
  use_ssl: true


